[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

# Redirect API calls to functions
[[redirects]]
  from = "/api/db/*"
  to = "/.netlify/functions/:splat"
  status = 200

# CORS headers for all API routes
[[headers]]
  for = "/api/db/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, OPTIONS"
